# Config file used by Multi Labeller https:github.commarketplaceactionsmulti-labeler

version: v1

labels:
  - label: "os:macOS"
    matcher:
      title: "mac"
  - label: "os:aix"
    matcher:
      title: "aix"
  - label: "os:windows"
    matcher:
      title: "windows"

  - label: "arch:arm32"
    matcher:
      title: "arm32"
  - label: "arch:arm64"
    matcher:
      title: "arm64"
  - label: "arch:ppc64le (pLinux)"
    matcher:
      title: "ppc64le"
  - label: "arch:s390x (zLinux)"
    matcher:
      title: "s390x"
  - label: "arch:x64"
    matcher:
      title: "x64"

  - label: "provider:aws"
    matcher:
      title: "aws"
  - label: "provider:azure"
    matcher:
      title: "azure"
  - label: "provider:ibmcloud"
    matcher:
      title: "ibmcloud"
  - label: "provider:linaro"
    matcher:
      title: "linaro"
  - label: "provider:marist"
    matcher:
      title: "marist"
  - label: "provider:osuosl"
    matcher:
      title: "osuosl"
  - label: "provider:scaleway"
    matcher:
      title: "scaleway"

  - label: "docker"
    matcher:
      title: "docker"
  - label: "hacktoberfest"
    matcher:
      body: "hacktoberfest"
  - label: "Nagios"
    matcher:
      title: "nagios"
  - label: "openj9"
    matcher:
      title: "openj9"
  - label: "Vagrant"
    matcher:
      title: "vagrant"
