name: Ansible Playbook

on:
  pull_request:
    paths:
    - .github/workflows/build_solaris.yml
    - ansible/**
    branches:         
    - master
  push:
    branches:         
    - master

jobs:
  build-solaris:
    name: Solaris
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Vagrant
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        wget https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.deb -O /tmp/vagrant_2.2.5_x86_64.deb
        sudo dpkg -i /tmp/vagrant_2.2.5_x86_64.deb
        rm -rf Vagrantfile
        vagrant init tnarik/solaris10-minimal

    - name: Install Virtualbox
      run: |
        wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
        wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian bionic contrib"
        sudo apt-get update
        sudo apt-get -y install virtualbox-6.0

    - run: |
        cd ansible
        ln -sf Vagrantfile.Centos6 Vagrantfile
        rm -f id_rsa.pub id_rsa
        # Copy the machine's ssh key for the VMs to use, after removing prior files
        ssh-keygen -q -f $PWD/id_rsa -t rsa -N ''
        vagrant up
        vagrant ssh -c uname -a
