on: 
    pull_request_target:
        types: [opened, edited, ready_for_review, reopened]
    issue_comment:

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: Label bot
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.comment.body }}"
